version: '2'
services:

    cicd:
        extends:
           file: devops/cicd/docker-compose.yml
           service: cicd
        build:
            context: .
            dockerfile: cicd/Dockerfile
        image: 'easydevops/cicd'
        environment:
            - 'DOCKER_TARGET=tcp://adc-swarm-master.eastus.cloudapp.azure.com:4243'
            - 'GIT_URL=https://github.com/andresfuentes/Checklist.git'
            - 'HEALTH_CHECK=http://adc-swarm-master.eastus.cloudapp.azure.com:8080/management/health'
            - 'DOCKER_PASSWORD=tresm1104'
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/Applications/Docker.app/Contents/Resources/bin/docker:/usr/bin/docker"
            - "/Applications/Docker.app/Contents/Resources/bin/docker-compose:/usr/bin/docker-compose"
            - "$PWD:/var/jenkins_home"
            - "$PWD:/var/app"
            - "$HOME/.m2:/root/.m2"

    app:
        extends:
           file: devops/infrastructure/swarm/docker-compose.yml
           service: builder
        build:
            context: .
            dockerfile: Dockerfile
        image: 'easydevops/builder'
        environment:
            - 'constraint:tier.app==true'
            - 'affinity:container!=~*app*'



