version: '2'
services:

    cicd:
        # extends:
        #    file: devops/cicd/docker-compose.yml
        #    service: cicd
        build:
            context: .
            dockerfile: cicd/Dockerfile
        image: 'easydevops/cicd'
        environment:
            - 'DOCKER_TARGET=tcp://172.10.10.20:4243'
            - 'GIT_URL=https://github.com/andresfuentes/Checklist.git'
            - 'HEALTH_CHECK=tcp://172.10.10.20:8080'
            - 'APP_NAME=builder'
            - 'DOCKER_USER=andresfuentes'
            - 'DOCKER_REPO=easydevops'
            - 'DOCKER_PASSWORD=tresm1104'
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/usr/bin/docker:/usr/bin/docker"
            - "/usr/bin/docker-compose:/usr/bin/docker-compose"
            - "/var/jenkins_home:/var/jenkins_home"
            - "$PWD:/var/app"
            - "$HOME/.m2:/root/.m2"

    app:
        # extends:
        #    file: devops/infrastructure/swarm/docker-compose.yml
        #    service: builder
        build:
            context: .
            dockerfile: Dockerfile
        image: 'easydevops/builder'
        environment:
            - 'DEFAULT_USERNAME=pwc'
            - 'DEFAULT_PASSWORD=pwc!123'
            - 'APP_NAME=checklist'
            - 'GIT_CICD_URL=https://github.com/andresfuentes/DevOpsSampleBuilder.git'
            - 'GIT_URL=https://github.com/andresfuentes/DevOpsSampleApp.git'
            - 'constraint:node.role==manager'
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/usr/bin/docker:/usr/bin/docker"
            - "/var/jenkins_home:/var/jenkins_home"
        ports:
            - '8080:8080'
            - '50000:50000'



