version: '2'
services:

    cicd:
        build:
            context: .
            dockerfile: devops/cicd/Dockerfile
        image: 'doghouze/cicd'
        environment:
            - 'DOCKER_TARGET=tcp://adc-tst-swarm-master.eastus.cloudapp.azure.com:4243'
            - 'HEALTH_CHECK=tcp://adc-tst-swarm-master.eastus.cloudapp.azure.com:8080'
            - 'APP_NAME=builder'
            - 'DOCKER_USER=andresfuentes'
            - 'DOCKER_REPO=easydevops'
            - 'DOCKER_PASSWORD={password}'
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/usr/bin/docker:/usr/bin/docker"
            - "/var/jenkins_home:/var/jenkins_home"
            - "$PWD:/var/app"
            - "$HOME/.m2:/root/.m2"

    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: 'doghouze/builder'
        environment:
            - 'DEFAULT_USERNAME=pwc'
            - 'DEFAULT_PASSWORD={password}'
            - 'APP_NAME=checklist'
            - 'GIT_CICD_URL=https://github.com/andresfuentes/DevOpsSampleBuilder.git'
            - 'GIT_URL=https://github.com/andresfuentes/DevOpsSampleApp.git'
            - 'constraint:node.role==manager'
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/usr/bin/docker:/usr/bin/docker"
            - "/var/jenkins_home:/var/jenkins_home"
        ports:
            - '8080:8080'
            - '50000:50000'



